### ISSUE TITLE
Doubt about security with postgre

### ISSUE THREAD

**Issue by chemabc** [felixfbecker/node-sql-template-strings#4]
Good afternoon, 

Thanks for this very usable tool!
I am start using it, but I have a security doubt. Taking your example: 
<pre><code>// is better written as
db.query(SQL`
  INSERT
  INTO    books
          (name, author, isbn, category, recommended_age, pages, price)
  VALUES  (${name}, ${author}, ${isbn}, ${category}, ${recommendedAge}, ${pages}, ${price})
`)
 </code></pre>
In my case I have two variables: 
<pre> <code>
//Example:
var fields = '(name, author, isbn, category, recommended_age, pages, price)';<br/>
var values = " 'john', 'leCarre', '67163716', 'book', 18, 223, 49.99 ";

//so my query would be:

db.query(SQL`
  INSERT
  INTO    books ${fields}
  VALUES  (${values})
`)
 </code></pre>
My question would be: in terms of security (sql injection), is this query as safe as when you write one by one every field and value?

Thanks a lot!

**Comment by felixfbecker** [comment]
@chemabc Your query will not work that way. sql-tempalte-strings only produces prepared statements.

```js
var fields = '(name, author, isbn, category, recommended_age, pages, price)';
var values = " 'john', 'leCarre', '67163716', 'book', 18, 223, 49.99 ";
console.log(SQL`
  INSERT
  INTO    books ${fields}
  VALUES  (${values})
`)
```
would result in
```js
{text: 'INSERT INTO books $1 VALUES ($2)', values: ['(name, author, isbn, category, recommended_age, pages, price)', "'john', 'leCarre', '67163716', 'book', 18, 223, 49.99 "]}
```
Which is not valid SQL. You can only insert individual values, like the examples in the readme, and then they are 100% safe because $x-references are inserted and the values passed as an array.

**Comment by chemabc** [comment]
Ok, thanks. Sql actually was working, but anyway I understand the risk. 
I will rewrite the code then. 
Thanks a lot for your help @felixfbecker!

**Comment by felixfbecker** [comment]
@chemabc I don't have much experience with Postgres, but from my understanding a prepared statement is only interpolated on the server side if you assign a name to it (see readme), and that interpolation is strict, secure and has performance benefits. Did you do that?

Because otherwise it might be that the pg client simply replaced all `$n` with the values without caring if interpolation at that point in the query is actually valid. For example, placeholders in the table name or the column names are not valid. I would always avoid client side interpolation because it is not as secure and has no performance benefits.
